### PR TITLE
 SQL: fix function definition of ticket_dependee_missing

### LINKED ISSUE #199: The _status component shows "dependee ticket missing", but it's not.
The changes of #182 seem to have introduced the incorrect behaviour, that the status of dependent tickets is nearly always reported as "dependee ticket is missing" while it is actually present.

### PR DESCRIPTION
**Pull request by a-tze**
SQL: fix function definition of ticket_dependee_missing, fixes #199

### CODE REVIEW

**Comment by a-tze** [comment]
Interesting suggesstion... I'll try to refactor the function and EXPLAIN it.

**Comment by a-tze** [comment]
Maybe you missed that "ep" and "epv" are also SELECTed, even before "tbl_ticket dependee" (of course this is only the view of an imperative programmer with the concept of lazy evaluation in mind and doesn't actually apply here).
However, if the order of joins is reversed, then "ep" and "epv" are at the end of the JOIN chain, nothing gained. The execution plan is almost identical for both versions, and the estimated costs are completely equal on my system (4.43..24.75). 
I'm not sure if PostgreSQL would use some shortcuts when doing the actual query. 

For me it was more obvious to "crawl" from the given depending ticket to the unknown dependee ticket.

Another approach to get rid of all those JOINS (in multiple places) would be to keep track of the dependee via a dedicated column in tbl_ticket. It is seldomly changed but read extremely often (view_servicable_tickets etc.)

**Comment by jjeising** [comment]
> Another approach to get rid of all those JOINS (in multiple places) would be to keep track of the dependee via a dedicated column in tbl_ticket.

If we do that we should combine the effort with other planed cached values and columns, see #167.

**Comment by a-tze** [comment]
> If we do that we should combine the effort with other planed cached values and columns, see #167.

Of course, but the intention of this PR was bugfixing.

File: src/Application/Migrations/18_function_ticket_dependency_missing.sql [hunk 1]
```diff
@@ -37,7 +37,7 @@ BEGIN
 	WHERE
 		depender.id = param_depender_ticket_id;
 
-	RETURN result;
+	RETURN COALESCE(result, true);
```
Comment (pegro) [inline src/Application/Migrations/18_function_ticket_dependency_missing.sql]: Now I'm confused. So we change the default return value to true? But the comment above the functions explains: "In all other cases, including the cases where this check does not make any sense, it will return false."
Which one is wrong now?

Comment (pegro) [reply src/Application/Migrations/18_function_ticket_dependency_missing.sql]: Also, I fail to reproduce the issue which is meant to be fixed with this.
What are the circumstances to reproduce this?

Comment (a-tze) [reply src/Application/Migrations/18_function_ticket_dependency_missing.sql]: The failing circumstances are: you have encoding tickets that have a depending profile as their profile. If they are e.g. in state "ready to encode" and you go into the detail view of the webapp, you do not get the green "indicator" (left of edit button) but you get an amber indicator, stating that the dependee ticket is missing while this is not true at all.

I will try to align the comments with the new behaviour.

**Comment by a-tze** [comment]
Turns out, the actual bugfix comes from not returning null, but changing the default return value to true was indeed wrong.
